language: cpp

compiler:
  - gcc
  - clang

before_install:
  - ./scripts/build_cmake.sh

script:
  - ./scripts/check_syntax.sh
  - ./scripts/build.sh

notifications:
    email:
      on_failure: change
