language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get -qq update

script:
  - ./scripts/check_syntax.sh
  - ./scripts/build.sh

notifications:
    email:
      on_failure: change
