language: cpp
sudo: required

compiler:
  - gcc
  - clang

before_install:
  - ./scripts/install_cmake.sh

script:
  - ./scripts/check_syntax.sh
  - ./scripts/build.sh

notifications:
    email:
      on_failure: change
